### ISSUE TITLE
ros2_adapter_fmi?

### ISSUE THREAD

**Issue by CThuleHansen** [boschresearch/fmi_adapter_ros2#1]
Hi, this looks very interesting.
Do you have anything going the other way?
I.e. an FMU tool-wrapping ROS or similar?

Cheers,
Casper

**Comment by ralph-lange** [comment]
Hi @CThuleHansen , I'm not aware of a specific tool for the other way around. MATLAB/Simulink has toolboxes for both worlds, FMI and ROS. Perhaps it is possible to create such a wrapper with it.
Best regards, Ralph

**Comment by CThuleHansen** [comment]
Hi Ralph,
Thank you.
Are you aware of any particular technical difficulties in doing it the other way around?
Otherwise we might attempt such a solution.

Do you by chance participate in the FMI design meeting in the end of February?

Cheers,
Casper

**Comment by ralph-lange** [comment]
Hi Casper, the most "difficult" technical question that comes immediately into my mind is the clock. The clock may be used internally by a ROS node in computations (e.g., for control functions) and triggers the timers inside the node. ROS provides a simulation clock mechanism for this purpose, cf. http://wiki.ros.org/Clock for an introduction to it. (The Wiki page is for classical ROS, but ROS 2 provides the same concept.)
I will not participate in the FMI design meeting, but my colleague @chrbertsch.
Cheers, Ralph

**Comment by CThuleHansen** [comment]
Hi @ralph-lange , thank you very much.
If you are interested, then I can write you a comment in here with our repo once we get started.

**Comment by ralph-lange** [comment]
Hi @CThuleHansen , sure I'm interested! Yes, please share the link here once the repo has been set up.

**Comment by CThuleHansen** [comment]
I'll close this issue once I have provided a link.

**Comment by CThuleHansen** [comment]
We are currently using rabbitmq to bridge the two: https://github.com/INTO-CPS-Association/fmu-rabbitmq https://into-cps-rabbitmq-fmu.readthedocs.io/en/latest/
