### ISSUE TITLE
Released versions reference nonexistent branches

### ISSUE THREAD

**Issue by mjcarroll** [boschresearch/fmi_adapter_ros2#3]
`fmi_adapter_ros2` was previously released for:

* Dashing: https://github.com/ros/rosdistro/pull/21346/files
* Eloquent: https://github.com/ros/rosdistro/pull/22880/files

But those releases now reference branches that aren't on this repository.  

Can you please update your releases to reflect what it should be now?

Tracking Issue: https://github.com/ros/rosdistro/issues/26853

**Comment by mjcarroll** [comment]
CC: @nuclearsandwich as Dashing Boss.

**Comment by ralph-lange** [comment]
This was my fault. Sorry! I just fixed it manually (not using bloom) in https://github.com/ros/rosdistro/pull/27120.
