### ISSUE TITLE
fmi adapter and micro-ROS

### ISSUE THREAD

**Issue by Zarnack** [boschresearch/fmi_adapter_ros2#6]
Hi,
I recognized that there is a lot of [development](https://www.bosch.com/stories/bringing-robotics-middleware-onto-tiny-microcontrollers/) happening to enable ROS2 on microcontrollers.   
Are there any future plans to put the fmi adapter onto micro-ROS as well?  
I am aware of possible performance issues, but I imagine that simple (PID) controllers could be simulated on an ESP32 or a Teensy board.

Best regards
Sebastian

**Comment by ralph-lange** [comment]
Hi Sebastian,
The fmi_adapter uses dynamic linking to execute a given (co-simulation) FMU. Such linking is generally not available in real-time operating systems (RTOS) for the microcontrollers targeted by micro-ROS. Even if an RTOS supports dynamic loading of binary modules, the mechanism is very specific for that RTOS.
However, there are efforts towards a separate standard named eFMI (FMI for embedded systems) for the exchange of physics-based models between modeling/simulation environments and software development environments for microcontrollers. An alpha release of eFMI has been published recently in the publicly-funded project [EMPHYSIS](https://emphysis.github.io/). In this project, not only eFMI was developed, but also prototypical implementations for the whole tool chain from physics-based modeling environments to production code on microcontrollers.
Integrating eFMI with micro-ROS would be mainly a matter of generating micro-ROS interfaces for the embedded Code generated by appropriate eFMI tools.
Best regards, Ralph

**Comment by Zarnack** [comment]
Thank you very much for this quick and elaborated answer. 
This project sounds very exciting and I am looking forward to its development :)
